before_install:
 - echo "MAVEN_OPTS='-Xmx2g -XX:+TieredCompilation -XX:TieredStopAtLevel=1'" > ~/.mavenrc

language: java

jdk:
 - oraclejdk8
 
services:
 - redis-server

script:
 - mvn clean verify -B -U

after_success:
   - mvn coveralls:report

cache:
  directories:
  - "$HOME/.m2"
